Fix modules and import names in sources
Use the same name when declaring a module and importing one.

The error which were generated over modules and imports, such as
`../src/libtt/env.d(11): Error: module define is in file
'libtt/define.d' which cannot be read` has been fixed.

The error was that by using src/libtt as module directory,
`import libtt.define` was searching for `src/libtt/libtt/define.d`.

By moving `include_directories` from src/meson.build to its parent
dir, the `-I=src/libtt/` (and the build relative `-I=../src/libtt`)
arguments have been transformed to `-I=src` and `-I=../src`;
this way the import statement looks in the correct directory.